version: '2'
services:
  granite-lite-server:
    container_name: granite-lite-server
    build: .
    ports:
      - '5222:5222'
#      - '8181:8181'
    environment:
      JAVA_OPTS: -Xmx512m -Xms256m
#      JAVA_OPTS: -Xmx512m -Xms256m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8181,suspend=n